version: '3.8'

services:

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: serve --listen 5000 --single /home/realestkma/app/dist
    env_file:
      - ./backend/.env.dev
    expose:
      - 5000
    environment:
      - VIRTUAL_PORT=5000
      - VIRTUAL_PATH=/

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn -c gunicorn.conf.py src.wsgi:application
    expose:
      - 8000
    env_file:
      - ./backend/.env.dev
    environment:
      - VIRTUAL_PATH=~^/(api|admin)/
    volumes:
      - static_volume:/home/realestkma/app/staticfiles
      - media_volume:/home/realestkma/app/mediafiles
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env.dev
    
  redis:
    image: redis:7-alpine
    restart: always
    expose:
      - 6379

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command:  celery -A src worker -l INFO
    restart: always
    env_file:
      - ./backend/.env.dev
    depends_on:
      - redis

  nginx-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 8080:80
      # - 443:443
    volumes:
      - static_volume:/home/realestkma/app/staticfiles
      - media_volume:/home/realestkma/app/mediafiles
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web
      - api


volumes:
  postgres_data:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme:
