# Generated by Django 4.0.4 on 2022-05-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='uid',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='USER ID'),
        ),
    ]
