# Generated by Django 4.0.4 on 2022-05-26 13:53

import creator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_alter_appuser_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='uid',
            field=models.CharField(default=creator.models.get_random_int, editable=False, max_length=50, unique=True, verbose_name='USER ID'),
        ),
    ]
