# Generated by Django 4.0.4 on 2022-06-04 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_openuser_openuser_unique_openuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(limit_value=8), django.core.validators.RegexValidator(inverse_match=True, message='Password cannot contain spaces', regex='\\s')], verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='openuser',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='The last time this Openuser profile was updated', verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='openuser',
            name='name',
            field=models.CharField(help_text='The name of this Openuser profile. Spaces are replaces with underscores', max_length=10, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='openuser',
            name='profile_password',
            field=models.CharField(default='p@ssw0rd', help_text='The password to use for all profiles', max_length=20, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Profile password cannot contain spaces', regex='\\s')], verbose_name='Profile password'),
        ),
        migrations.AlterField(
            model_name='openuser',
            name='profiles',
            field=models.IntegerField(default=5, help_text='Number of openuser profiles to create, defaul is 5', validators=[django.core.validators.MaxValueValidator(limit_value=50)], verbose_name='Profiles'),
        ),
    ]
