# Generated by Django 4.0.4 on 2022-06-08 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_alter_openuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openuser',
            name='name',
            field=models.CharField(help_text='The name of this Openuser profile. Spaces are replaces with underscores', max_length=20, validators=[django.core.validators.RegexValidator(message='Must begin with a letter. Can only contain letters, numbers and hyphens', regex='^[a-zA-Z]+[\\w -]*'), django.core.validators.MinLengthValidator(limit_value=4)], verbose_name='Name'),
        ),
    ]
