# Generated by Django 4.0.4 on 2022-05-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_alter_appuser_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='uid',
            field=models.IntegerField(default=127040768520179284731052407333003091156, unique=True, verbose_name='USER ID'),
        ),
    ]
