# Generated by Django 4.0.4 on 2022-08-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0003_appuser_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='auth_provider_token',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Provider Authentication Token'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='auth_provider',
            field=models.CharField(blank=True, choices=[('Email', 'Email'), ('Github', 'Github'), ('Google', 'Google'), ('Twitter', 'Twitter')], default='Email', max_length=50, null=True, verbose_name='Authentication Provider'),
        ),
    ]
