# Generated by Django 4.0.4 on 2022-05-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0003_alter_appuser_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email address belongs to another account'}, max_length=255, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Username not available'}, max_length=255, unique=True, verbose_name='Username'),
        ),
    ]
