# Generated by Django 4.0.4 on 2022-05-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0004_alter_appuser_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='uid',
            field=models.IntegerField(unique=True, verbose_name='USER ID'),
        ),
    ]
