# Generated by Django 4.0.4 on 2022-05-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0005_alter_appuser_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='uid',
            field=models.CharField(max_length=50, unique=True, verbose_name='USER ID'),
        ),
    ]
