# Generated by Django 4.0.4 on 2022-05-28 22:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0007_alter_appuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(limit_value=8, message='Password should be at least 8 characters in length')], verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'This username is not available'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Username can only contain letters, numbers and underscore', regex='\\W'), django.core.validators.MinLengthValidator(limit_value=4, message='Username should be at least 4 characters in length')], verbose_name='Username'),
        ),
    ]
