# Generated by Django 4.0.4 on 2022-06-22 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0007_alter_openuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openuser',
            name='profiles',
            field=models.IntegerField(default=5, help_text='Number of openuser profiles to create, defaul is 5', validators=[django.core.validators.MaxValueValidator(limit_value=25), django.core.validators.MinValueValidator(limit_value=1)], verbose_name='Profiles'),
        ),
    ]
