# Generated by Django 4.0.4 on 2022-06-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0008_alter_openuser_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='openuser',
            name='endpoint',
            field=models.URLField(blank=True, help_text='Url endpoint for your openuser profiles', max_length=255, null=True, verbose_name='Endpoint'),
        ),
    ]
