# Generated by Django 4.0.4 on 2022-06-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0009_openuser_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='openuser',
            name='status',
            field=models.CharField(choices=[('Creating', 'Creating'), ('Created', 'Created')], default='Creating', help_text='Openuser status', max_length=50, verbose_name='Status'),
        ),
    ]
