# Generated by Django 4.0.4 on 2022-06-25 12:11

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0010_openuser_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='openuser',
            name='unique_openuser',
        ),
        migrations.AddConstraint(
            model_name='openuser',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('creator', 'name'), name='unique_openuser'),
        ),
    ]
