# Generated by Django 4.0.4 on 2022-06-05 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0013_alter_openuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openuser',
            name='profile_password',
            field=models.CharField(default='p@ssw0rd', help_text='The password to use for all profiles', max_length=20, validators=[django.core.validators.RegexValidator(message='Profile password cannot contain spaces', regex='^[a-zA-Z]+[a-zA-Z0-9]*')], verbose_name='Profile password'),
        ),
    ]
