# Generated by Django 4.0.4 on 2022-06-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0019_alter_openuser_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openuser',
            options={'ordering': ['-date_created']},
        ),
    ]
