# Generated by Django 4.0.4 on 2022-06-05 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0021_alter_openuser_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openuser',
            name='profile_password',
            field=models.CharField(default='p@ssw0rd', help_text='The password to use for all profiles', max_length=15, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Profile password cannot contain spaces', regex='\\s')], verbose_name='Profile password'),
        ),
    ]
