# Generated by Django 4.0.4 on 2022-08-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_alter_openuser_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='auth_provider',
            field=models.CharField(blank=True, default='Email', max_length=50, null=True, verbose_name='Authentication Provider'),
        ),
    ]
