# Generated by Django 4.0.4 on 2022-08-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0004_appuser_auth_provider_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='auth_provider_token',
        ),
        migrations.AddField(
            model_name='appuser',
            name='auth_provider_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Authentication Provider Token'),
        ),
    ]
