# Generated by Django 4.0.4 on 2022-08-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0005_remove_appuser_auth_provider_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='auth_provider_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Authentication Provider ID'),
        ),
        migrations.AlterField(
            model_name='openuser',
            name='status',
            field=models.CharField(choices=[('Creating', 'Creating'), ('Created', 'Created')], default='Created', help_text='Openuser status', max_length=50, verbose_name='Status'),
        ),
    ]
