# Generated by Django 4.0.4 on 2022-08-26 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0006_alter_appuser_auth_provider_id_alter_openuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('----', 'Undefined')], default='----', max_length=7, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='openuser',
            name='name',
            field=models.CharField(help_text='The name of this Openuser profile. Spaces are replaced with underscores', max_length=20, validators=[django.core.validators.RegexValidator(message='Must begin and end with a letter. And can only contain letters, numbers and hyphens', regex='^[a-zA-Z]([\\w -]*[a-zA-Z])?$'), django.core.validators.MinLengthValidator(limit_value=4)], verbose_name='Name'),
        ),
    ]
