# Generated by Django 4.0.4 on 2022-08-29 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0007_appuser_gender_alter_openuser_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Openuser',
            new_name='Openuserapp',
        ),
    ]
