# Generated by Django 4.0.4 on 2022-09-03 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0009_alter_openuserapp_profiles'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='openuserapp',
            name='unique_openuser',
        ),
        migrations.AlterField(
            model_name='openuserapp',
            name='profiles',
            field=models.IntegerField(default=2, help_text='Number of openuser profiles to create, default is 2', validators=[django.core.validators.MaxValueValidator(limit_value=25), django.core.validators.MinValueValidator(limit_value=2)], verbose_name='Profiles'),
        ),
        migrations.AddConstraint(
            model_name='openuserapp',
            constraint=models.UniqueConstraint(fields=('creator', 'name'), name='unique_openuser'),
        ),
    ]
