# Generated by Django 4.0.4 on 2022-09-16 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0010_remove_openuserapp_unique_openuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openuserapp',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='openuserapp',
            name='profiles',
            field=models.IntegerField(default=2, help_text='Number of openuser profiles to create, default is 2', validators=[django.core.validators.MaxValueValidator(limit_value=50), django.core.validators.MinValueValidator(limit_value=2)], verbose_name='Profiles'),
        ),
    ]
