# Generated by Django 4.0.4 on 2022-10-01 12:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0011_openuserapp_description_alter_openuserapp_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openuserapp',
            name='name',
            field=models.CharField(help_text='The name of this Openuser profile.', max_length=20, validators=[django.core.validators.RegexValidator(message='Must begin and end with a letter. And can only contain letters, numbers and hyphens', regex='^[a-zA-Z]([\\w -]*[a-zA-Z])?$'), django.core.validators.MinLengthValidator(limit_value=4)], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='openuserapp',
            name='profile_password',
            field=models.CharField(default='p@ssw0rd', help_text='The password to use for all profiles', max_length=15, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Profile password cannot contain spaces', regex='\\s'), django.core.validators.MinValueValidator(limit_value=8)], verbose_name='Profile password'),
        ),
        migrations.AlterField(
            model_name='openuserapp',
            name='profiles',
            field=models.IntegerField(default=5, help_text='Number of openuser profiles to create, default is 5', validators=[django.core.validators.MaxValueValidator(limit_value=50), django.core.validators.MinValueValidator(limit_value=5)], verbose_name='Profiles'),
        ),
    ]
