# This action deploys my containerized apps. Uses docker-compose up to start app
# For some reason, docker-compose up does not update changes. so i had to add
# more run steps

name: CD Deploy (AWS)

on:
  workflow_dispatch:


jobs:
  deploy-app:

    runs-on: self-hosted

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      
      - name: Ping AWS
        run:  ping -c4 aws.amazon.com
      
      - name: Show docker containers
        run:  docker compose -f docker-compose.prod.yml ps -a

      - name: Run docker compose up
        run:  docker compose -f docker-compose.prod.yml up --detach --build