# This action assumes that flake8 package is in the requirements.txt file.


name: CI Lint flake8


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-lint-with-flake8:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Pyton ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run:  |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run:  |
          flake8 .
